### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by YoungFaithful**
- Changes of load_timeseries_data to take personal data (file or folder)
- Tutorial `workflow_introduction.jl`
- Question: Why do we have FullInput data as a return of load_timeseries_data?

### CODE REVIEW

**Comment by holgerteichgraeber** [comment]
Great. I'll work on the workflow intro file. 
- Could you also add windows and macos to travis? 
- Does the interface to load_timeseries_data() for the old loading of CEP timeseries data change? My impression is no (which is good).

**Comment by YoungFaithful** [comment]
- osx testing included
- Windows not available

**Comment by holgerteichgraeber** [comment]
Were there any pushes that still need to be added, or can I push this to dev and master?

**Comment by YoungFaithful** [comment]
> Were there any pushes that still need to be added, or can I push this to dev and master?

Let me push one thing and than we could merge.

**Comment by YoungFaithful** [comment]
Done @holgerteichgraeber

**Pull request merged**
